---
name: "CI"

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - stable-*
  workflow_dispatch:

jobs:
  build-import:
    uses: ansible/ansible-content-actions/.github/workflows/build_import.yaml@main
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main
    with:
      extra_matrix_entries: >
        [
          {
            "description": "Sanity tests using ansible-core 2.16 and python 3.10",
            "factors": ["sanity", "py3.10", "2.16"],
            "name": "sanity-py3.10-2.16",
            "python": "3.10"
          },
          {
            "description": "Sanity tests using ansible-core 2.16 and python 3.11",
            "factors": ["sanity", "py3.11", "2.16"],
            "name": "sanity-py3.11-2.16",
            "python": "3.11"
          },
          {
            "description": "Sanity tests using ansible-core 2.16 and python 3.12",
            "factors": ["sanity", "py3.12", "2.16"],
            "name": "sanity-py3.12-2.16",
            "python": "3.12"
          }
        ]
  unit-galaxy:
    uses: ansible/ansible-content-actions/.github/workflows/unit.yaml@main
    with:
      extra_matrix_entries: >
          [
            {
              "description": "Unit tests using ansible-core 2.16 and python 3.10",
              "factors": ["unit", "py3.10", "2.16"],
              "name": "unit-py3.10-2.16",
              "python": "3.10"
            },
            {
              "description": "Unit tests using ansible-core 2.16 and python 3.11",
              "factors": ["unit", "py3.11", "2.16"],
              "name": "unit-py3.11-2.16",
              "python": "3.11"
            },
            {
              "description": "Unit tests using ansible-core 2.16 and python 3.12",
              "factors": ["unit", "py3.12", "2.16"],
              "name": "unit-py3.12-2.16",
              "python": "3.12"
            }
          ]
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ansible_version: "milestone"
      python_version: "3.12"
    steps:
      - name: Checkout collection
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Install ansible-core (${{ env.ansible_version }})
        run: >-
          python3 -m pip install
          https://github.com/ansible/ansible/archive/${{ env.ansible_version }}.tar.gz
          --disable-pip-version-check
        shell: bash

      - name: Build and install collection
        id: install-collection
        uses: ansible-network/github_actions/.github/actions/build_install_collection@main
        with:
          install_python_dependencies: false
          source_path: .

      - name: Set up git
        run: |
          git config --global user.email gha@localhost
          git config --global user.name "Github Actions"
        shell: bash

      - name: Run integration tests
        uses: ansible-network/github_actions/.github/actions/ansible_test_integration@main
        with:
          collection_path: ${{ steps.install-collection.outputs.collection_path }}
          python_version: ${{ env.python_version }}
          ansible_version: ${{ env.ansible_version }}
          ansible_test_requirement_files: 'test-requirements.txt'
          ansible_test_environment: |
            ANSIBLE_TEST_GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}
  all_green:
    if: ${{ always() }}
    needs:
      - build-import
      - sanity
      - unit-galaxy
      - ansible-lint
      - integration
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.sanity.result }}',
          '${{ needs.unit-galaxy.result }}',
          '${{ needs.ansible-lint.result }}',
          '${{ needs.build-import.result }}',
          '${{ needs.integration.result }}'
          ])"
